safe: true
markdown: kramdown
highlighter: pygments
permalink: /:categories/:title
exclude: [stylobate, all.styl, style.styl, style_ie.styl, font_regular.styl]

production_url: http://kizu.ru
relative_permalinks: false

github_repo: "kizu/kizu.github.com"

link_handles:
    - prefix: "@"
      handle: "https://twitter.com/"
    - prefix: "gh:"
      handle: "https://github.com/"

langs:
    - ru
    - en

default_lang: ru

# flat_categories:
#    - "fun"
#    - "issues"

prose:
    rooturl: "_posts"
    metadata:
        "_posts": |

            categories: drafts

            layout: post

            published: "true"

        "_posts/fun": |

            categories: fun

            layout: post

            published: "true"

        "_posts/issues": |

            categories: issues

            layout: post

            published: "true"

        "_posts/blog": |

            categories: blog

            layout: post

            published: "true"

        "_posts/en": |

            categories: en drafts

            layout: post

            published: "true"

        "_posts/en/fun": |

            categories: en fun

            layout: post

            published: "true"

        "_posts/en/issues": |

            categories: en issues

            layout: post

            published: "true"

        "_posts/en/blog": |

            categories: en blog

            layout: post

            published: "true"
